[identity]
name = "libpcap"
version = "1.10.4"
category = "networking"
description = """
System-independent interface for user-level packet capture, used by network analysis and security tools such as nmap.
"""

[build]
steps = ["""
echo "[COGMAN] Extracting libpcap source, sir."
tar -xf tar/libpcap-1.10.4.tar.gz -C source --strip-components=1
""", """
echo "[COGMAN] Configuring libpcap, sir."
export CPPFLAGS="-I$PKGROOT/usr/include"
export LDFLAGS="-L$PKGROOT/usr/lib"

cd build
../source/configure \
  --prefix=/usr \
  --disable-static \
  --with-pcap=linux
""", """
echo "[COGMAN] Building libpcap, sir."
cd build
make
"""]

[installer]
steps = ["""
echo "[COGMAN] Installing libpcap into pkgroot, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]