[identity]
name = "nano"
version = "7.2"
category = "base"
summary = """
GNU Nano text editor for terminal
"""

[source]
kind = "tarball"
file = "nano-7.2.tar.xz"

[dependencies]
build = ["toolchain/gcc", "base/ncurses"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting nano source, sir."
tar -xf tar/nano-7.2.tar.xz -C source
""", """
echo "[COGMAN] Configuring nano, sir."
cd build
../source/nano-7.2/configure --prefix=/usr \
  --sysconfdir=/etc \
  --enable-utf8
"""]

[installer]
steps = ["""
echo "[COGMAN] Building nano, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing nano into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]