[identity]
name = "tar"
version = "1.35"
category = "base"
summary = """
GNU Tar archiving utility for tape archives
"""

[source]
kind = "tarball"
file = "tar-1.35.tar.xz"

[dependencies]
build = ["toolchain/gcc"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting tar source, sir."
tar -xf tar/tar-1.35.tar.xz -C source
""", """
echo "[COGMAN] Configuring tar, sir."
cd build
../source/tar-1.35/configure --prefix=/usr \
  
"""]

[installer]
steps = ["""
echo "[COGMAN] Building tar, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing tar into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]