[identity]
name = "gmp"
version = "6.3.0"
category = "toolchain"
summary = """
GNU Multiple Precision Arithmetic Library for arbitrary precision math
"""

[source]
kind = "tarball"
file = "gmp-6.3.0.tar.xz"

[dependencies]
build = ["toolchain/gcc"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting gmp source, sir."
tar -xf tar/gmp-6.3.0.tar.xz -C source
""", """
echo "[COGMAN] Configuring gmp, sir."
cd build
../source/gmp-6.3.0/configure --prefix=/usr \
  --enable-cxx
"""]

[installer]
steps = ["""
echo "[COGMAN] Building gmp, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing gmp into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]