[identity]
name = "dos2unix"
version = "7.5.2"
category = "additional"
summary = """
Text file format converter between DOS and Unix formats
"""

[source]
kind = "tarball"
file = "dos2unix-7.5.2.tar.xz"

[dependencies]
build = ["toolchain/gcc"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting dos2unix source, sir."
tar -xf tar/dos2unix-7.5.2.tar.xz -C source
""", """
echo "[COGMAN] Building dos2unix, sir."
cd source/dos2unix-7.5.2
make -j$(nproc)
"""]

[installer]
steps = ["""
echo "[COGMAN] Building dos2unix, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing dos2unix into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]