[identity]
name = "xfsprogs"
version = "6.6.0"
category = "system"
summary = """
XFS filesystem administration utilities
"""

[source]
kind = "tarball"
file = "xfsprogs-6.6.0.tar.xz"

[dependencies]
build = ["toolchain/gcc"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting xfsprogs source, sir."
tar -xf tar/xfsprogs-6.6.0.tar.xz -C source
""", """
echo "[COGMAN] Configuring xfsprogs, sir."
cd build
../source/xfsprogs-6.6.0/configure --prefix=/usr \
  
"""]

[installer]
steps = ["""
echo "[COGMAN] Building xfsprogs, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing xfsprogs into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]