[identity]
name = "mksh"
version = "59c"
category = "additional"
summary = """
MirBSD Korn Shell POSIX compatible shell
"""

[source]
kind = "tarball"
file = "mksh-59c.tar.xz"

[dependencies]
build = ["toolchain/gcc"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting mksh source, sir."
tar -xf tar/mksh-59c.tar.xz -C source
""", """
echo "[COGMAN] Building mksh, sir."
cd source/mksh-59c
make -j$(nproc)
"""]

[installer]
steps = ["""
echo "[COGMAN] Building mksh, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing mksh into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]