# Rogue Linux logrotate configuration
weekly
rotate 4
compress
delaycompress
missingok
notifempty

/var/log/syslog {
    rotate 3
    size 1M
    postrotate
        killall -HUP syslogd 2>/dev/null || true
    endscript
}

/var/log/*.log {
    rotate 4
    size 512k
}
