[identity]
name = "libmnl"
version = "1.0.5"
category = "networking"
description = """
Minimalistic user-space library for Netlink communication.
"""

[build]
steps = ["""
echo "[COGMAN] Extracting libmnl source, sir."
tar -xf tar/libmnl-1.0.5.tar -C source --strip-components=1
""", """
echo "[COGMAN] Configuring libmnl, sir."
cd source
./configure --prefix=/usr
""", """
echo "[COGMAN] Building libmnl, sir."
cd source
make
"""]

[installer]
steps = ["""
echo "[COGMAN] Installing libmnl into pkgroot, sir."
cd source
make install
"""]

[policy]