[identity]
name = "dash"
version = "0.5.12"
category = "additional"
summary = """
Debian Almquist Shell POSIX compliant lightweight shell
"""

[source]
kind = "tarball"
file = "dash-0.5.12.tar.xz"

[dependencies]
build = ["toolchain/gcc"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting dash source, sir."
tar -xf tar/dash-0.5.12.tar.xz -C source
""", """
echo "[COGMAN] Configuring dash, sir."
cd build
../source/dash-0.5.12/configure --prefix=/usr \
  
"""]

[installer]
steps = ["""
echo "[COGMAN] Building dash, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing dash into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]