[identity]
name = "pv"
version = "1.8.5"
category = "additional"
summary = """
Pipe Viewer for monitoring progress of data through pipeline
"""

[source]
kind = "tarball"
file = "pv-1.8.5.tar.xz"

[dependencies]
build = ["toolchain/gcc"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting pv source, sir."
tar -xf tar/pv-1.8.5.tar.xz -C source
""", """
echo "[COGMAN] Configuring pv, sir."
cd build
../source/pv-1.8.5/configure --prefix=/usr \
  
"""]

[installer]
steps = ["""
echo "[COGMAN] Building pv, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing pv into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]