[identity]
name = "parallel"
version = "20240222"
category = "additional"
summary = """
Shell tool for executing jobs in parallel using resources
"""

[source]
kind = "tarball"
file = "parallel-20240222.tar.xz"

[dependencies]
build = ["toolchain/perl"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting parallel source, sir."
tar -xf tar/parallel-20240222.tar.xz -C source
""", """
echo "[COGMAN] Building parallel, sir."
cd source/parallel-20240222
make -j$(nproc)
"""]

[installer]
steps = ["""
echo "[COGMAN] Building parallel, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing parallel into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]