[identity]
name = "shadow"
version = "4.15.1"
category = "base"
summary = """
Password and user account management utilities
"""

[source]
kind = "tarball"
file = "shadow-4.15.1.tar.xz"

[dependencies]
build = ["toolchain/gcc", "base/linux-pam"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting shadow source, sir."
tar -xf tar/shadow-4.15.1.tar.xz -C source
""", """
echo "[COGMAN] Configuring shadow, sir."
cd build
../source/shadow-4.15.1/configure --prefix=/usr \
  --sysconfdir=/etc \
  --disable-static \
  --with-libpam \
  --without-selinux
"""]

[installer]
steps = ["""
echo "[COGMAN] Building shadow, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing shadow into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]