[identity]
name = "automake"
version = "1.17"
category = "toolchain"
summary = """
GNU Automake Makefile generator
"""

[source]
kind = "tarball"
file = "automake-1.17.tar.xz"

[dependencies]
build = ["toolchain/autoconf", "toolchain/perl"]

[build]
steps = ["rm -rf source build", "mkdir -p source build", """
echo "[COGMAN] Extracting automake source, sir."
tar -xf tar/automake-1.17.tar.xz -C source
""", """
echo "[COGMAN] Configuring automake, sir."
cd build
../source/automake-1.17/configure --prefix=/usr \
  
"""]

[installer]
steps = ["""
echo "[COGMAN] Building automake, sir."
cd build
make -j$(nproc)
""", """
echo "[COGMAN] Installing automake into staging root, sir."
cd build
make install DESTDIR="$PKGROOT"
"""]

[policy]